"""
Step 6 — Real-ESRGAN fine-tuning on the CCTV dataset (paired data).

Fine-tunes the pretrained RealESRGAN_x4plus generator on the LR/HR frame
pairs produced by Step 2, fulfilling the thesis objective of training the
model with hyperparameter adjustment (learning rate, batch size, number
of iterations are set in config.py and logged with the run).

After training, the fine-tuned generator is run on all LR frames and the
results are saved to output/sr_finetuned/ for comparison in Step 7.

Requires an NVIDIA GPU with CUDA. With the default 5000 iterations, expect
roughly an hour on an RTX 4070 Ti (2-3 hours on a Colab T4).

Usage:
    python step6_finetune_esrgan.py                 # train + inference
    python step6_finetune_esrgan.py --iters 2000    # shorter training run
    python step6_finetune_esrgan.py --skip-train    # inference only (weights exist)
"""

import sys
import subprocess
import argparse
import shutil
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import (
    FRAMES_HR_DIR, FRAMES_LR_DIR, FRAMES_SR_FT_DIR,
    REALESRGAN_DIR, REALESRGAN_REPO_URL,
    ESRGAN_WEIGHTS, ESRGAN_FT_WEIGHTS,
    SCALE_FACTOR, FINETUNE_ITERS, FINETUNE_LR, FINETUNE_BATCH,
)


def install_deps():
    pkgs = ['basicsr', 'realesrgan', 'facexlib', 'gfpgan',
            'torch', 'torchvision', 'opencv-python', 'numpy', 'tqdm', 'pyyaml']
    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q'] + pkgs, check=True)


def patch_basicsr():
    """Fix the known basicsr/torchvision import incompatibility.

    Recent torchvision removed transforms.functional_tensor; basicsr 1.4.2
    still imports rgb_to_grayscale from it. Redirect the import so training
    works with recent torchvision versions.
    """
    import basicsr
    deg = Path(basicsr.__file__).parent / 'data' / 'degradations.py'
    src = deg.read_text(encoding='utf-8')
    bad = 'from torchvision.transforms.functional_tensor import rgb_to_grayscale'
    good = 'from torchvision.transforms.functional import rgb_to_grayscale'
    if bad in src:
        deg.write_text(src.replace(bad, good), encoding='utf-8')
        print('Patched basicsr degradations.py (torchvision compatibility).')


def clone_repo():
    if REALESRGAN_DIR.exists():
        print(f'Real-ESRGAN repo found: {REALESRGAN_DIR}')
        return
    print('Cloning Real-ESRGAN repository...')
    subprocess.run(['git', 'clone', '--depth', '1', REALESRGAN_REPO_URL,
                    str(REALESRGAN_DIR)], check=True)


def write_meta_info() -> Path:
    """Paired meta_info file: '<hr_relpath>, <lr_relpath>' per line."""
    meta = REALESRGAN_DIR / 'meta_info_cctv_pairs.txt'
    hr_frames = sorted(FRAMES_HR_DIR.glob('*.png'))
    lines = []
    for hr in hr_frames:
        lr = FRAMES_LR_DIR / hr.name
        if lr.exists():
            lines.append(f'{hr.name}, {hr.name}')
    meta.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Meta info written: {meta}  ({len(lines)} pairs)')
    return meta


def write_train_yaml(iters: int, meta_info: Path) -> Path:
    """Training configuration for basicsr (paired dataset, generator + GAN)."""
    yml = REALESRGAN_DIR / 'options' / 'finetune_cctv_pairdata.yml'
    yml.parent.mkdir(parents=True, exist_ok=True)
    yml.write_text(f"""# Fine-tune RealESRGAN_x4plus on CCTV paired data (generated by step6)
name: finetune_RealESRGANx4plus_cctv
model_type: RealESRGANModel
scale: {SCALE_FACTOR}
num_gpu: auto
manual_seed: 0

# No on-the-fly degradation: we train on the fixed synthetic pairs of Step 2
high_order_degradation: False

gt_usm: True

datasets:
  train:
    name: CCTV-pairs
    type: RealESRGANPairedDataset
    dataroot_gt: {FRAMES_HR_DIR.as_posix()}
    dataroot_lq: {FRAMES_LR_DIR.as_posix()}
    meta_info: {meta_info.as_posix()}
    io_backend:
      type: disk
    gt_size: 256
    use_hflip: True
    use_rot: False
    use_shuffle: True
    num_worker_per_gpu: 2
    batch_size_per_gpu: {FINETUNE_BATCH}
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: {SCALE_FACTOR}

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

path:
  pretrain_network_g: {ESRGAN_WEIGHTS.as_posix()}
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: ~
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float {FINETUNE_LR}
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float {FINETUNE_LR}
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [{int(iters * 0.8)}]
    gamma: 0.5

  total_iter: {iters}
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1000
  use_tb_logger: False
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
""", encoding='utf-8')
    print(f'Training config written: {yml}')
    return yml


def run_training(yml: Path):
    print('\nLaunching fine-tuning (this takes a while)...\n')
    subprocess.run(
        [sys.executable, 'realesrgan/train.py', '-opt', str(yml), '--auto_resume'],
        cwd=str(REALESRGAN_DIR), check=True,
    )


def export_weights(iters: int):
    """Copy the last EMA checkpoint to weights/RealESRGAN_x4plus_finetuned.pth."""
    exp_dir = REALESRGAN_DIR / 'experiments' / 'finetune_RealESRGANx4plus_cctv' / 'models'
    candidates = sorted(exp_dir.glob('net_g_*.pth'),
                        key=lambda p: int(p.stem.split('_')[-1]) if p.stem.split('_')[-1].isdigit() else -1)
    if not candidates:
        print(f'ERROR: No checkpoint found in {exp_dir}')
        sys.exit(1)
    last = candidates[-1]
    shutil.copy2(last, ESRGAN_FT_WEIGHTS)
    print(f'Fine-tuned weights exported: {last.name} → {ESRGAN_FT_WEIGHTS}')


def run_inference(tile: int):
    import cv2
    import torch
    from tqdm import tqdm
    from basicsr.archs.rrdbnet_arch import RRDBNet
    from realesrgan import RealESRGANer

    model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=23,
                    num_grow_ch=32, scale=SCALE_FACTOR)
    upsampler = RealESRGANer(
        scale=SCALE_FACTOR, model_path=str(ESRGAN_FT_WEIGHTS), model=model,
        tile=tile, tile_pad=10, pre_pad=0, half=torch.cuda.is_available(),
    )

    lr_frames = sorted(FRAMES_LR_DIR.glob('*.png'))
    FRAMES_SR_FT_DIR.mkdir(parents=True, exist_ok=True)
    print(f'\nRunning fine-tuned model on {len(lr_frames)} LR frames...')
    for lr_path in tqdm(lr_frames, unit='frame'):
        img = cv2.imread(str(lr_path), cv2.IMREAD_COLOR)
        if img is None:
            continue
        output, _ = upsampler.enhance(img, outscale=SCALE_FACTOR)
        cv2.imwrite(str(FRAMES_SR_FT_DIR / lr_path.name), output)

    count = len(list(FRAMES_SR_FT_DIR.glob('*.png')))
    print(f'Saved to: {FRAMES_SR_FT_DIR}  ({count} files)')


def main():
    parser = argparse.ArgumentParser(description='Step 6: Fine-tune Real-ESRGAN on CCTV pairs')
    parser.add_argument('--iters', type=int, default=FINETUNE_ITERS,
                        help=f'Total training iterations (default: {FINETUNE_ITERS})')
    parser.add_argument('--skip-train', action='store_true',
                        help='Skip training; run inference with existing fine-tuned weights')
    parser.add_argument('--tile', type=int, default=0,
                        help='Tile size for inference (0=no tiling)')
    args = parser.parse_args()

    install_deps()
    patch_basicsr()
    import torch

    print('=' * 60)
    print('STEP 6 — Real-ESRGAN fine-tuning on CCTV paired data')
    print('=' * 60)
    print(f'  Iterations    : {args.iters}')
    print(f'  Learning rate : {FINETUNE_LR}')
    print(f'  Batch size    : {FINETUNE_BATCH}')
    print()

    if not torch.cuda.is_available() and not args.skip_train:
        print('ERROR: Fine-tuning requires an NVIDIA GPU with CUDA available.')
        sys.exit(1)

    if not args.skip_train:
        if not ESRGAN_WEIGHTS.exists():
            print(f'ERROR: Base weights not found: {ESRGAN_WEIGHTS}')
            print('       Run step3_esrgan_inference.py first (it downloads them).')
            sys.exit(1)
        hr_count = len(list(FRAMES_HR_DIR.glob('*.png')))
        if hr_count == 0:
            print(f'ERROR: No HR frames in {FRAMES_HR_DIR}. Run step2 first.')
            sys.exit(1)
        print(f'Training pairs available: {hr_count}')

        clone_repo()
        meta = write_meta_info()
        yml = write_train_yaml(args.iters, meta)
        run_training(yml)
        export_weights(args.iters)
    elif not ESRGAN_FT_WEIGHTS.exists():
        print(f'ERROR: --skip-train given but {ESRGAN_FT_WEIGHTS} does not exist.')
        sys.exit(1)

    run_inference(args.tile)
    print('\nStep 6 complete. Run step7_compute_metrics.py next.')


if __name__ == '__main__':
    main()
